name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://fitness-platform-prod.firebaseapp.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install web dependencies
      run: |
        cd apps/web
        npm ci

    - name: Run tests
      run: npm run test

    - name: Build web application
      run: |
        cd apps/web
        npm run build

    - name: Setup Firebase CLI
      uses: w9jds/setup-firebase@main
      with:
        tools: cli
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}

    - name: Configure production environment
      run: |
        cp firebase.prod.json firebase.json
        cp firestore.prod.rules firestore.rules

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        firebase deploy --project fitness-platform-prod --non-interactive

    - name: Notify deployment success
      if: success()
      run: |
        echo "🎉 Production deployment successful!"
        echo "🌐 Live at: https://fitness-platform-prod.firebaseapp.com"